spring:
  profiles:
    active: local
  jackson:
    deserialization:
      accept-single-value-as-array: true
spring.batch.job.names: ${job.name:NONE}
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/real_estate
      username: ch
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql