
spring:
  profiles:
    active: rds-mariadb-migration
  config:
    import: openapi.yml
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jackson:
    deserialization:
      accept-single-value-as-array: true
  bjdCode:
    path: "src/main/resources/bjdcode.txt"

---
spring:
  config:
    activate:
      on-profile: local-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/hogangyes?rewriteBatchedStatements=true
    username: root
    password: dockermysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: rds-mariadb
  datasource:
    url: jdbc:mariadb://batch-estate-engine-backup.chiy2uou2gt3.ap-northeast-2.rds.amazonaws.com:3306/batch_estate_engine
    username: chaehyun
    password: chaehyunttak
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false

---
spring:
  config:
    activate:
      on-profile: rds-mariadb-migration
  datasource:
    url: jdbc:mariadb://batch-estate-engine-backup.chiy2uou2gt3.ap-northeast-2.rds.amazonaws.com:3306/batch_estate_engine
    username: chaehyun
    password: chaehyunttak
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
