spring:
  main:
    web-application-type: none
  profiles:
    active: local
  jackson:
    deserialization:
      accept-single-value-as-array: true
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch_real_estate?rewriteBatchedStatements=true
    username: root
    password: Lch885233@
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.names:createRealEstateJob}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  config:
    activate:
      on-profile: local