spring:
  profiles:
    active: local
  config:
    import: openapi.yml
  main:
    web-application-type: none
  batch:
    jdbc:
      initialize-schema: always
    job:
      names: ${job.names:createRealEstateJob}
  jackson:
    deserialization:
      accept-single-value-as-array: true
  bjdCode:
    path: "src/main/resources/bjdcode.txt"

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/hogangyes?rewriteBatchedStatements=true
    username: root
    password: dockermysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false